const SESSION_FILTERS = {
  NEARME: {
    VALUE: "NEARME",
    TEXT: "NEAR ME"
  },
  ALL: {
    VALUE: "ALL",
    TEXT: "ALL"
  }
};

const DEFAULT_SEARCH_RADIUS = 50; //50km
const MAX_SEARCH_DISTANCE = 200; // 200km

export { SESSION_FILTERS, DEFAULT_SEARCH_RADIUS, MAX_SEARCH_DISTANCE };
